### ISSUE TITLE
Updates in bootloader broke keyboard handler

### ISSUE THREAD

**Issue by crazykid080** [crazykid080/osdev#1]
In 8bca86c9a970531dd64f39a557da4b9e9a9fcda2 I started refactoring the bootloader using the code from Nanobyte's livestream. I got around halfway and was able to boot into the kernel and celebrated by attempting to put text on screen, however the keyboard handler is now bugged and the cursor skips, hitting the enter key functions as a space, and the space key functions as return.. according to debug log the scancodes are correct. Let's hope this fixes itself when I finish the bootloader refactor

![image](https://github.com/crazykid080/osdev/assets/10173541/b9e279fa-6680-40dd-9000-9b3674d5e93d)

**Comment by crazykid080** [comment]
After doing some debug testing it appears that the setcursor function in vga_text is being called twice for some reason

![image](https://github.com/crazykid080/osdev/assets/10173541/62b65e1c-ea96-4211-837b-e6afc51997dd)

**Comment by isedwards** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
privatenation, @darcstar-solutions, @Bruces1, @NaviJee, @1blob4, @guidra-rev, @SoloSx, @XL-Reaper, @hack3r-0m, @hulkkii, @desrochesf, @Matt-hue, @leighsmithh, @tonymds, @arsmn, @Komroncube, @ssantoshp, @SabbanIndustrial, @AndresVanegasC, @mumtazhaqiqy, @botasylum, @robin2010liu, @RyzeNGrind, @heromanba, @gaius-qi, @ravel44, @eduardo911, @senthil28, @chasebolt, @jamestylerboyd, @angshuman-agarwal, @nunesgh, @as20aa, @stella3d, @rogerhuanglife, @Mcoy-lab, @namar0x0309, @lcividin, @brunowego, @flp09, @we1l1n, @itsmepsk, @alenny811, @datamaster64, @ruijiexie, @matf5, @HankiGreed, @himalayagarg, @RalphVita, @dabenman

**Comment by crazykid080** [comment]
Fixed in b1c228f
